### ISSUE TITLE
Pre-trained Model

### ISSUE THREAD

**Issue by thefiend** [multimedia-eurecat/ELFW#1]
Hi 

I would like to know if it is possible for you to share the pre-trained model for use. I have also submitted the form to obtain the dataset so that I can train a model with them. Hope you can expedite the process of approval. Currently working on a project and require a high accuracy model to detect headdress and spectacle.

**Comment by valillon** [comment]
Hi there,

We are not currently releasing the trained weights. Maybe in the future, but I can't tell when. However, as you mentioned, it should be straightforward once having the dataset and code. Please have a try and tell if you experience any trouble.

**Comment by test1230-lab** [comment]
what gpu(s) were used for training?

**Comment by StateGovernment** [comment]
Hi @valillon,

Since, you've mentioned you'd providing the models sometime in the future, I'm just checking if you guys have decided to release the pretained models by now.

Thanks

**Comment by valillon** [comment]
No advances on this regard. Moreover, after fixing #7, models deserve to be re-trained. But tbh as time goes by, it is more unlikely we re-train and release any model. So please, do not account on that.

Anyway, again, everything required to train those models has been already released.
So, it should be really straightforward.
