### ISSUE TITLE
gcnX used in demo files

### ISSUE THREAD

**Issue by thefiend** [multimedia-eurecat/ELFW#2]
Hi, wish to check what is the package gcnX used in the "EUT_ELFW_singleimage_colab.ipynb" demo file. Can't seem to find it anywhere in the project and online.
<img width="496" alt="Screenshot 2020-08-17 at 8 33 21 AM" src="https://user-images.githubusercontent.com/3714496/90347675-5ffd2b00-e064-11ea-87c6-6403100ab7c8.png">

**Comment by valillon** [comment]
GCN is currently in the `models.py` file.
It was originally defined in an old file named `gcnX.py`.
This commit [c395e2ba](https://github.com/multimedia-eurecat/ELFW/commit/master) should have fixed it.

**Comment by test1230-lab** [comment]
is the deeplab included in this deeplabv3 or deeplabv3+?
