### ISSUE TITLE
Is the dataset link availble?

### ISSUE THREAD

**Issue by DanielMao2015** [multimedia-eurecat/ELFW#8]
Hi, EFLW dataset plays a big role in face segmentation. And I have applied the dataset, but have not gotten any response yet. I don know whether the dataset link is still maintained by someone.

**Comment by valillon** [comment]
Dear @DanielMao2015, ELFW can be requested from the [Project Site](https://multimedia-eurecat.github.io/2020/06/22/extended-faces-in-the-wild.html).
A download notification has been just sent to you.
Thanks for your interest.

**Comment by roopeshn28** [comment]
Hi, EFLW dataset plays a big role in face segmentation. And I have applied the dataset, but have not gotten any response yet. I don't know whether the dataset link is still maintained by someone.
